# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: wosdummy.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto


class PostVisibility(betterproto.Enum):
    """Post visibility"""

    POST_VISIBILITY_UNSPECIFIED = 0
    POST_VISIBILITY_PUBLIC = 1
    POST_VISIBILITY_PRIVATE = 2
    POST_VISIBILITY_FRIENDS_ONLY = 3


class UserStatus(betterproto.Enum):
    """User status"""

    USER_STATUS_UNSPECIFIED = 0
    USER_STATUS_ACTIVE = 1
    USER_STATUS_INACTIVE = 2
    USER_STATUS_BANNED = 3


@dataclass
class AddCommentRequest(betterproto.Message):
    """Add comment request"""

    post_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    content: str = betterproto.string_field(3)


@dataclass
class ListPostsRequest(betterproto.Message):
    """List posts request with pagination"""

    page_size: int = betterproto.int32_field(1)
    page_token: str = betterproto.string_field(2)
    visibility_filter: "PostVisibility" = betterproto.enum_field(3)
    tag_filters: List[str] = betterproto.string_field(4)


@dataclass
class ListUserPostsRequest(betterproto.Message):
    """List user's posts request"""

    user_id: str = betterproto.string_field(1)
    page_size: int = betterproto.int32_field(2)
    page_token: str = betterproto.string_field(3)
    visibility_filter: "PostVisibility" = betterproto.enum_field(4)


@dataclass
class UpdatePostRequest(betterproto.Message):
    """Update post request"""

    id: str = betterproto.string_field(1)
    # Fields to update
    title: str = betterproto.string_field(2)
    content: str = betterproto.string_field(3)
    image_urls: List[str] = betterproto.string_field(4)
    tags: List[str] = betterproto.string_field(5)
    visibility: "PostVisibility" = betterproto.enum_field(6)
    clear_images: bool = betterproto.bool_field(7)
    clear_tags: bool = betterproto.bool_field(8)


@dataclass
class ListCommentsResponse(betterproto.Message):
    """List comments response"""

    comments: List["Comment"] = betterproto.message_field(1)
    next_page_token: str = betterproto.string_field(2)
    total_count: int = betterproto.int32_field(3)


@dataclass
class ListCommentsRequest(betterproto.Message):
    """List comments request"""

    post_id: str = betterproto.string_field(1)
    page_size: int = betterproto.int32_field(2)
    page_token: str = betterproto.string_field(3)


@dataclass
class GetUserRequest(betterproto.Message):
    """Get user request"""

    id: str = betterproto.string_field(1)


@dataclass
class CreateUserRequest(betterproto.Message):
    """Create user request"""

    username: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)
    password: str = betterproto.string_field(3)
    display_name: str = betterproto.string_field(4)
    profile_picture_url: str = betterproto.string_field(5)
    bio: str = betterproto.string_field(6)


@dataclass
class GetPostRequest(betterproto.Message):
    """Get post request"""

    id: str = betterproto.string_field(1)


@dataclass
class User(betterproto.Message):
    """User entity"""

    id: str = betterproto.string_field(1)
    username: str = betterproto.string_field(2)
    email: str = betterproto.string_field(3)
    display_name: str = betterproto.string_field(4)
    profile_picture_url: str = betterproto.string_field(5)
    bio: str = betterproto.string_field(6)
    created_at: datetime = betterproto.message_field(7)
    updated_at: datetime = betterproto.message_field(8)
    status: "UserStatus" = betterproto.enum_field(9)


@dataclass
class CreatePostRequest(betterproto.Message):
    """Create post request"""

    user_id: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    content: str = betterproto.string_field(3)
    image_urls: List[str] = betterproto.string_field(4)
    tags: List[str] = betterproto.string_field(5)
    visibility: "PostVisibility" = betterproto.enum_field(6)


@dataclass
class ListPostsResponse(betterproto.Message):
    """List posts response"""

    posts: List["Post"] = betterproto.message_field(1)
    next_page_token: str = betterproto.string_field(2)
    total_count: int = betterproto.int32_field(3)


@dataclass
class AuthenticateResponse(betterproto.Message):
    """Authentication response"""

    user_id: str = betterproto.string_field(1)
    access_token: str = betterproto.string_field(2)
    refresh_token: str = betterproto.string_field(3)
    expires_in: int = betterproto.int64_field(4)


@dataclass
class DeleteUserRequest(betterproto.Message):
    """Delete user request"""

    id: str = betterproto.string_field(1)


@dataclass
class AuthenticateRequest(betterproto.Message):
    """Authentication request"""

    username_or_email: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class LikePostRequest(betterproto.Message):
    """Like post request"""

    post_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)


@dataclass
class Post(betterproto.Message):
    """Post entity"""

    id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    title: str = betterproto.string_field(3)
    content: str = betterproto.string_field(4)
    image_urls: List[str] = betterproto.string_field(5)
    tags: List[str] = betterproto.string_field(6)
    visibility: "PostVisibility" = betterproto.enum_field(7)
    like_count: int = betterproto.int32_field(8)
    comment_count: int = betterproto.int32_field(9)
    created_at: datetime = betterproto.message_field(10)
    updated_at: datetime = betterproto.message_field(11)


@dataclass
class ListUsersResponse(betterproto.Message):
    """List users response"""

    users: List["User"] = betterproto.message_field(1)
    next_page_token: str = betterproto.string_field(2)
    total_count: int = betterproto.int32_field(3)


@dataclass
class UpdateUserRequest(betterproto.Message):
    """Update user request"""

    id: str = betterproto.string_field(1)
    # Fields to update with optional values
    email: str = betterproto.string_field(2)
    display_name: str = betterproto.string_field(3)
    profile_picture_url: str = betterproto.string_field(4)
    bio: str = betterproto.string_field(5)
    status: "UserStatus" = betterproto.enum_field(6)


@dataclass
class Comment(betterproto.Message):
    """Comment entity"""

    id: str = betterproto.string_field(1)
    post_id: str = betterproto.string_field(2)
    user_id: str = betterproto.string_field(3)
    content: str = betterproto.string_field(4)
    created_at: datetime = betterproto.message_field(5)
    updated_at: datetime = betterproto.message_field(6)


@dataclass
class DeletePostRequest(betterproto.Message):
    """Delete post request"""

    id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)


@dataclass
class LikePostResponse(betterproto.Message):
    """Like post response"""

    updated_like_count: int = betterproto.int32_field(1)


@dataclass
class UnlikePostRequest(betterproto.Message):
    """Unlike post request"""

    post_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)


@dataclass
class ListUsersRequest(betterproto.Message):
    """List users request with pagination"""

    page_size: int = betterproto.int32_field(1)
    page_token: str = betterproto.string_field(2)
    status_filter: "UserStatus" = betterproto.enum_field(3)
